/**
 * Telemetry Domain Events
 *
 * Discriminated union of all events that can flow through the telemetry bus.
 * Each event has a `kind` discriminator used by both producers (hooks) and
 * consumers (WS broadcast, port-file writer) for exhaustive switch handling.
 *
 * Design notes:
 * - All events are JSON-serializable (Date → number, Map → object).
 * - `id` is generated by the bus (monotonic, per-process) — producers must NOT set it.
 * - `ts` is wall-clock ms since epoch (set by the bus).
 * - Keep payloads small; the dashboard renders them as list items.
 */

export type EventKind =
	| "lsp_progress"
	| "lsp_diagnostic"
	| "sqlite_stats"
	| "index_started"
	| "index_file_started"
	| "index_file_done"
	| "index_file_failed"
	| "index_done"
	| "ws_client_connected"
	| "ws_client_disconnected"
	| "server_started"
	| "server_stopped"
	| "bus_overflow"
	| "tool_started"
	| "tool_completed"
	| "tool_failed";

interface BaseEvent {
	readonly id: number;
	readonly ts: number;
}

export interface LspProgressEvent extends BaseEvent {
	readonly kind: "lsp_progress";
	readonly file: string;
	readonly current: number;
	readonly total: number;
	readonly stage:
		| "preparing"
		| "lsp_open"
		| "parsing"
		| "extracting"
		| "building_edges"
		| "resolving"
		| "persisting"
		| "cleanup"
		| "done";
}

export interface LspDiagnosticEvent extends BaseEvent {
	readonly kind: "lsp_diagnostic";
	readonly file: string;
	readonly line: number;
	readonly severity: "error" | "warning" | "info" | "hint";
	readonly message: string;
}

export interface SqliteStatsEvent extends BaseEvent {
	readonly kind: "sqlite_stats";
	readonly pous: number;
	readonly variables: number;
	readonly types: number;
	readonly relationships: number;
	readonly files: number;
	readonly dbBytes: number;
}

export interface IndexStartedEvent extends BaseEvent {
	readonly kind: "index_started";
	readonly workspace: string;
	readonly totalFiles: number;
}

export interface IndexFileStartedEvent extends BaseEvent {
	readonly kind: "index_file_started";
	readonly file: string;
	readonly index: number;
	readonly total: number;
}

export interface IndexFileDoneEvent extends BaseEvent {
	readonly kind: "index_file_done";
	readonly file: string;
	readonly index: number;
	readonly total: number;
	readonly entities: number;
	readonly edges: number;
	readonly durationMs: number;
}

export interface IndexFileFailedEvent extends BaseEvent {
	readonly kind: "index_file_failed";
	readonly file: string;
	readonly index: number;
	readonly total: number;
	readonly error: string;
}

export interface IndexDoneEvent extends BaseEvent {
	readonly kind: "index_done";
	readonly workspace: string;
	readonly indexedFiles: number;
	readonly skippedFiles: number;
	readonly totalEntities: number;
	readonly totalEdges: number;
	readonly totalTimeMs: number;
}

export interface WsClientConnectedEvent extends BaseEvent {
	readonly kind: "ws_client_connected";
	readonly remote: string;
}

export interface WsClientDisconnectedEvent extends BaseEvent {
	readonly kind: "ws_client_disconnected";
	readonly remote: string;
}

export interface ServerStartedEvent extends BaseEvent {
	readonly kind: "server_started";
	readonly pid: number;
	readonly bunVersion: string;
	readonly uiPort: number;
}

export interface ServerStoppedEvent extends BaseEvent {
	readonly kind: "server_stopped";
	readonly reason: "sigint" | "sigterm" | "error" | "manual";
}

export interface BusOverflowEvent extends BaseEvent {
	readonly kind: "bus_overflow";
	readonly dropped: number;
	readonly capacity: number;
}

/**
 * Correlation id shared across the three tool_* events for a single call.
 * Allows the UI to group `tool_started` → `tool_completed`/`tool_failed`
 * into one logical "AI call" row, even though they arrive as 2-3 separate events.
 */
export type ToolCallId = string & { readonly __brand: "ToolCallId" };

export interface ToolStartedEvent extends BaseEvent {
	readonly kind: "tool_started";
	readonly callId: ToolCallId;
	readonly tool: string;
	/** Sanitized args preview (strings truncated to 200 chars). */
	readonly argsPreview: string;
}

export interface ToolCompletedEvent extends BaseEvent {
	readonly kind: "tool_completed";
	readonly callId: ToolCallId;
	readonly tool: string;
	readonly durationMs: number;
	readonly ok: true;
}

export interface ToolFailedEvent extends BaseEvent {
	readonly kind: "tool_failed";
	readonly callId: ToolCallId;
	readonly tool: string;
	readonly durationMs: number;
	readonly ok: false;
	readonly error: string;
}

export type ToolEvent = ToolStartedEvent | ToolCompletedEvent | ToolFailedEvent;

export type TelemetryEvent =
	| LspProgressEvent
	| LspDiagnosticEvent
	| SqliteStatsEvent
	| IndexStartedEvent
	| IndexFileStartedEvent
	| IndexFileDoneEvent
	| IndexFileFailedEvent
	| IndexDoneEvent
	| WsClientConnectedEvent
	| WsClientDisconnectedEvent
	| ServerStartedEvent
	| ServerStoppedEvent
	| BusOverflowEvent
	| ToolStartedEvent
	| ToolCompletedEvent
	| ToolFailedEvent;

/**
 * Producer-side payload type: what callers pass to the bus BEFORE the bus
 * stamps `id` and `ts`. Discriminated by `kind` only.
 *
 * Built via distributed conditional so each union member is Omit'd individually
 * (this preserves the discriminant's literal type and per-kind payload).
 */
export type TelemetryEventDraft = TelemetryEvent extends infer E
	? E extends TelemetryEvent
		? Omit<E, "id" | "ts">
		: never
	: never;

/**
 * Type guard: produces a readable label for UI/dashboards.
 */
export function eventLabel(event: TelemetryEvent): string {
	switch (event.kind) {
		case "lsp_progress":
			return `[LSP] ${event.stage} ${event.current}/${event.total} ${event.file}`;
		case "lsp_diagnostic":
			return `[DIAG] ${event.severity} ${event.file}:${event.line} — ${event.message}`;
		case "sqlite_stats":
			return `[SQLite] pous=${event.pous} vars=${event.variables} types=${event.types} rels=${event.relationships} files=${event.files}`;
		case "index_started":
			return `[INDEX] started ${event.workspace} (${event.totalFiles} files)`;
		case "index_file_started":
			return `[INDEX] [${event.index}/${event.total}] START ${event.file}`;
		case "index_file_done":
			return `[INDEX] [${event.index}/${event.total}] DONE ${event.file} (${event.entities}e/${event.edges}r in ${event.durationMs}ms)`;
		case "index_file_failed":
			return `[INDEX] [${event.index}/${event.total}] FAIL ${event.file}: ${event.error}`;
		case "index_done":
			return `[INDEX] done ${event.workspace}: indexed=${event.indexedFiles} skipped=${event.skippedFiles} entities=${event.totalEntities} edges=${event.totalEdges} in ${event.totalTimeMs}ms`;
		case "ws_client_connected":
			return `[WS] +client ${event.remote}`;
		case "ws_client_disconnected":
			return `[WS] -client ${event.remote}`;
		case "server_started":
			return `[SRV] started pid=${event.pid} bun=${event.bunVersion} uiPort=${event.uiPort}`;
		case "server_stopped":
			return `[SRV] stopped reason=${event.reason}`;
		case "bus_overflow":
			return `[BUS] overflow: dropped ${event.dropped}/${event.capacity}`;
		case "tool_started":
			return `[TOOL] ⟶ ${event.tool} (${event.callId})`;
		case "tool_completed":
			return `[TOOL] ✓ ${event.tool} (${event.callId}) in ${event.durationMs}ms`;
		case "tool_failed":
			return `[TOOL] ✗ ${event.tool} (${event.callId}) in ${event.durationMs}ms: ${event.error}`;
	}
}
