/**
 * Bun-based build script.
 *
 * Compiles the TypeScript codebase into standalone executable binaries.
 *   1. bin/st-graph-rag-mcp.exe (MCP server)
 *   2. bin/obsidian-export.exe (CLI tool)
 *
 * Usage: bun run scripts/build.ts
 */

import { spawnSync } from "node:child_process";
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { basename, dirname, relative, resolve } from "node:path";

const projectRoot = resolve(import.meta.dir, "..");
const binDir = resolve(projectRoot, "bin");
const uiDir = resolve(projectRoot, "src/ui");
const uiDistDir = resolve(uiDir, "dist");

const entries = [
	{ input: "src/index.ts", output: "st-graph-rag-mcp", bundleUi: true },
	{ input: "src/cli/obsidian-export.ts", output: "obsidian-export" },
];

function collectFilesRecursive(dir: string): string[] {
	const out: string[] = [];
	const stack = [dir];
	while (stack.length > 0) {
		const cur = stack.pop();
		if (!cur) break;
		const entries = readdirSync(cur, { withFileTypes: true });
		for (const ent of entries) {
			const full = resolve(cur, ent.name);
			if (ent.isDirectory()) stack.push(full);
			else if (ent.isFile()) out.push(full);
		}
	}
	return out.sort();
}

function buildUi() {
	console.log(`[build] Building UI in ${relative(projectRoot, uiDir)}...`);
	const installRes = spawnSync("bun", ["install"], {
		cwd: uiDir,
		stdio: "inherit",
	});
	if (installRes.status !== 0) process.exit(1);
	const buildRes = spawnSync("bun", ["run", "build"], {
		cwd: uiDir,
		stdio: "inherit",
	});
	if (buildRes.status !== 0) process.exit(1);
}

function generateUiEmbedShim(files: readonly string[]): string {
	const shimPath = resolve(projectRoot, "src/ui-embed.gen.ts");
	const lines = [
		"// biome-ignore-all lint: generated file",
		"/** AUTO-GENERATED by scripts/build.ts */",
		"export const UI_ASSETS = Object.freeze({",
	];

	for (const file of files) {
		const rel =
			"/" +
			relative(resolve(projectRoot, "src/ui/dist"), file).replace(/\\/g, "/");
		const ext = file.split(".").pop()?.toLowerCase();
		let contentType = "application/octet-stream";
		if (ext === "html") contentType = "text/html";
		if (ext === "js" || ext === "mjs") contentType = "application/javascript";
		if (ext === "css") contentType = "text/css";
		if (ext === "svg") contentType = "image/svg+xml";

		const textContent = readFileSync(file, "utf8");
		lines.push(`  ${JSON.stringify(rel)}: Object.freeze({`);
		lines.push(`    contentType: ${JSON.stringify(contentType)},`);
		lines.push(`    content: ${JSON.stringify(textContent)}`);
		lines.push(`  }),`);
	}

	lines.push(
		`}) as Readonly<Record<string, Readonly<{ contentType: string, content: string }>>>;`,
	);
	lines.push("");
	writeFileSync(shimPath, lines.join("\n"), "utf8");
	return shimPath;
}

async function buildOnce() {
	if (!existsSync(binDir)) mkdirSync(binDir, { recursive: true });

	const startTime = performance.now();

	for (const entry of entries) {
		if (entry.bundleUi) {
			buildUi();
			const uiFiles = collectFilesRecursive(uiDistDir);
			generateUiEmbedShim(uiFiles);
			console.log(
				`[build] Embedding ${uiFiles.length} UI asset(s) as inline strings...`,
			);
		}

		const inputPath = resolve(projectRoot, entry.input);
		const outputPath = resolve(binDir, entry.output);

		console.log(`[build] Compiling ${entry.input} to binary...`);

		const result = spawnSync(
			"bun",
			["build", "--compile", inputPath, "--outfile", outputPath],
			{ stdio: "inherit", cwd: projectRoot },
		);

		if (result.status !== 0) {
			console.error(`[build] FAIL: Failed to compile ${entry.input}`);
			process.exit(1);
		}

		const exeExt = process.platform === "win32" ? ".exe" : "";
		const finalPath = outputPath + exeExt;

		if (existsSync(finalPath)) {
			const size = statSync(finalPath).size;
			console.log(
				`[build] ✓ ${entry.input} → ${relative(projectRoot, finalPath)} (${(size / 1024 / 1024).toFixed(1)} MB)`,
			);
		}
	}

	const elapsed = (performance.now() - startTime).toFixed(0);
	console.log(`[build] done in ${elapsed}ms`);
}

buildOnce().catch((err) => {
	console.error(err);
	process.exit(1);
});
