"""Generator for large_project.st — approx 100k LOC for benchmarking."""
import sys

HEADER = """(* Auto-generated benchmark corpus: ~100k LOC of Structured Text *)
(* Generated by tools/gen_large_st.py *)

{types}

{functions}

{function_blocks}

{programs}
"""

TYPE_TEMPLATE = """TYPE {name} :
STRUCT
    {fields}
END_STRUCT
END_TYPE
"""

FUNC_TEMPLATE = """FUNCTION {name} : {ret_type}
VAR_INPUT
    x : {input_type};
END_VAR
VAR
    i, j : DINT;
    tmp : {ret_type};
END_VAR

tmp := x;
FOR i := 1 TO 10 DO
    tmp := tmp + 1;
    IF tmp > 1000 THEN
        tmp := 0;
    END_IF
END_FOR
{name} := tmp;
END_FUNCTION
"""

FB_TEMPLATE = """FUNCTION_BLOCK {name}
VAR_INPUT
    enable : BOOL;
    setpoint : REAL;
END_VAR
VAR_OUTPUT
    status : INT;
    actual : REAL;
END_VAR
VAR
    counter : DINT;
    integrator : REAL;
    state : INT;
    buf : ARRAY[0..9] OF REAL;
END_VAR

CASE state OF
    0: (* Idle *)
        IF enable THEN
            state := 1;
            counter := 0;
            integrator := 0.0;
        END_IF
    1: (* Running *)
        counter := counter + 1;
        integrator := integrator + setpoint * 0.01;
        IF integrator > 100.0 THEN
            integrator := 100.0;
        ELSIF integrator < -100.0 THEN
            integrator := -100.0;
        END_IF
        actual := integrator;
        buf[counter MOD 10] := actual;
        IF counter > 1000 THEN
            state := 2;
        END_IF
    2: (* Done *)
        status := 1;
        IF NOT enable THEN
            state := 0;
            status := 0;
        END_IF
END_CASE

{methods}
END_FUNCTION_BLOCK
"""

METHOD_TEMPLATE = """METHOD {name} : {ret_type}
VAR_INPUT
    a, b : {input_type};
END_VAR
VAR
    result : {ret_type};
END_VAR

IF a > b THEN
    result := a;
ELSE
    result := b;
END_IF
{name} := result;
END_METHOD
"""

PROG_TEMPLATE = """PROGRAM {name}
VAR
    fb_{name}_1 : FB_{first_fb};
    fb_{name}_2 : FB_{second_fb};
    fb_{name}_3 : FB_{third_fb};
    fb_{name}_4 : FB_{fourth_fb};
    cycle_count : DINT;
    running : BOOL;
    temperature : REAL;
    pressure : REAL;
    flow_rate : REAL;
    level : REAL;
    alarms : ARRAY[0..7] OF BOOL;
    config : ConfigType_{config_idx};
END_VAR

running := TRUE;
cycle_count := cycle_count + 1;

fb_{name}_1(enable := running, setpoint := temperature);
fb_{name}_2(enable := running, setpoint := pressure);
fb_{name}_3(enable := running AND cycle_count MOD 2 = 0, setpoint := flow_rate);
fb_{name}_4(enable := cycle_count > 100, setpoint := level);

IF fb_{name}_1.status = 1 THEN
    alarms[0] := TRUE;
END_IF

temperature := fb_{name}_1.actual;
pressure := fb_{name}_2.actual;
flow_rate := fb_{name}_3.actual;
level := fb_{name}_4.actual;

CONFIG_TASK
    Single := MainTask;
    Interval := T#20ms;
    Priority := 1;
END_CONFIG_TASK
END_PROGRAM
"""


def gen_types(count):
    out = []
    for i in range(count):
        fields = "\n    ".join(f"field_{j} : DINT;" for j in range(6))
        out.append(TYPE_TEMPLATE.format(name=f"ConfigType_{i}", fields=fields))
    return "\n".join(out)


def gen_functions(count):
    out = []
    types = ["DINT", "REAL", "BOOL", "INT", "UDINT", "LREAL"]
    inputs = ["DINT", "REAL", "INT", "UDINT"]
    for i in range(count):
        out.append(
            FUNC_TEMPLATE.format(
                name=f"Calc_{i}",
                ret_type=types[i % len(types)],
                input_type=inputs[i % len(inputs)],
            )
        )
    return "\n".join(out)


def gen_function_blocks(count):
    out = []
    for i in range(count):
        methods = "\n".join(
            METHOD_TEMPLATE.format(
                name=f"GetMax_{j}",
                ret_type="REAL",
                input_type="REAL",
            )
            for j in range(3)
        )
        out.append(FB_TEMPLATE.format(name=f"FB_{i}", methods=methods))
    return "\n".join(out)


def gen_programs(count, total_fbs):
    out = []
    for i in range(count):
        out.append(
            PROG_TEMPLATE.format(
                name=f"Prog_{i}",
                first_fb=i % total_fbs,
                second_fb=(i + 1) % total_fbs,
                third_fb=(i + 2) % total_fbs,
                fourth_fb=(i + 3) % total_fbs,
                config_idx=i % 50,
            )
        )
    return "\n".join(out)


def main():
    num_types = 50
    num_functions = 800
    num_fbs = 600
    num_programs = 500

    types = gen_types(num_types)
    functions = gen_functions(num_functions)
    function_blocks = gen_function_blocks(num_fbs)
    programs = gen_programs(num_programs, num_fbs)

    content = HEADER.format(
        types=types,
        functions=functions,
        function_blocks=function_blocks,
        programs=programs,
    )

    with open("tests/data/large_project.st", "w", encoding="utf-8") as f:
        f.write(content)

    lines = content.count("\n")
    size = len(content)
    print(f"Generated large_project.st: {lines} lines, {size:,} bytes ({size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
